### PR TITLE
Give dof_handler to setup function instead of triangulation

### PR DESCRIPTION
**Pull request by bergbauer**

### CODE REVIEW

**Comment by nfehn** [comment]
how did you realize this or why did you only change the function call and not the implementation?

**Comment by bergbauer** [comment]
I had problems with compilation after pulling the newest deal master, in the implementation the `dof_handler` is requested

**Comment by nfehn** [comment]
So this is a bug which we did not detect so far because the triangulation could be interpreted as a DoFHandler before recent changes in deal.II? @kronbichler can you explain this?

**Comment by peterrum** [comment]
> So this is a bug which we did not detect so far because the triangulation could be interpreted as a DoFHandler before recent changes in deal.II?

Implicitly the constructor of `DoFHandler` was called. We labeled the constructor of `DoFHandler` that takes the `Triangulation` as explicit to prevent such issues (inside of the library) last week.

**Review by nfehn — APPROVED** [review]

**Pull request merged**
