### PR TITLE
Adapt to new class names in deal.II for evaluation

### PR DESCRIPTION
**Pull request by kronbichler**
Once https://github.com/dealii/dealii/pull/13056 gets merged, we need this change to compile ExaDG.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]

**Review by nfehn — APPROVED** [review]

**Comment by nfehn** [comment]
I add the "do not merge" label for clarity. @kronbichler please remove it and merge once deal.II's PR is done.

**Comment by kronbichler** [comment]
Yes, I forgot about the 9.3 compatibility. I forced-push a version which keeps the old code and adds a new path for the new version.

**Comment by nfehn** [comment]
I guess the related deal.II PR has been merged? I think it would make sense to document such information also here

**Comment by kronbichler** [comment]
Yes, https://github.com/dealii/dealii/pull/13056 was merged, but we should see it from the CI if the code is ready, as it should automatically aim to build both variants.

**Comment by nfehn** [comment]
> I add the "do not merge" label for clarity. @kronbichler please remove it and merge once deal.II's PR is done.

so it can be merged now?

**Pull request merged**
