### PR TITLE
remove "using namespace dealii"

### PR DESCRIPTION
**Pull request by nfehn**
I think it is advantageous to see dependencies on dealii explicitly in ExaDG. We do not want to expect ExaDG-developers to also be dealii-developers.

### CODE REVIEW

**Comment by nfehn** [comment]
I updated the wiki-page "coding conventions"

**Comment by nfehn** [comment]
I updated the wiki-page "coding conventions"

**Review by kronbichler — APPROVED** [review]
I agree on this change from an encapsulation perspective. Some of the places get a bit tedious to read, such as `dealii::Point` or `dealii::Tensor` that are rather unambiguous. We can always decide to pull certain data structures into ExaDG's namespace, such as we do for `CellIntegrator = dealii::FEEvaluation` (or decide not do it, depending on how our preferences develop). I did not check all occurrences but I assume that the compiler will signal any opportunity missed out (and that you grepped for `using namespace dealii` to eliminate all).

**Comment by nfehn** [comment]
One should check the files so that comments and std::cout output is not affected, as I did the changes somewhat automatically

**Pull request merged**
