### PR TITLE
Create a docker container config

### PR DESCRIPTION
**Pull request by kwic**
I created a Dockerfile for automated building of exadg Docker images. It comes with all dependencies preinstalled and compiled and makes it a breeze to start developing in exadg across all platforms. It is well suited for "bring your own environment" scenarios.
A further benefit is a tested install recipe for building ExaDG.

As I have no idea how the Github CI/CD or image registry function, someone with that knowledge needs to take over from here. Perhaps @peterrum can help?

### CODE REVIEW

**Comment by peterrum** [comment]
An option would be to use https://hub.docker.com/. In deal.II, this is what we use; once a PR is merged into master a Docker-image is created automatically with the following script https://github.com/dealii/dealii/blob/master/.github/workflows/docker.yml. Up to discussion it of course if we want to build deal.II on our own (as done in 4C) or we use one of the official images https://hub.docker.com/r/dealii/dealii/. Hope that helps.

**Comment by nfehn** [comment]
I think it needs input from @kwic to get this project done. Do you think there will be some resources for this or how should we proceed?

**Comment by kwic** [comment]
Pro building on to of the `dealii` container:
- saves a lot of build time
- compiler/dev environment is preconfigured
- Ubuntu is ok

Pro building everything:
- Single build tool. I'm not sure whether the `ninja` and `CMake` build combo would play nicely.
- Independent of deal.ii's choice of compiler and settings
- Deal.ii and ExaDG can be optimized platform specifically in one go

Considering ExaDG boasts extreme performance and benefits heavily from platform specific optimizations, the second options seem the logical one.

**Comment by nfehn** [comment]
I am closing this PR for now because of what @bergbauer did in PR #332 (see https://hub.docker.com/repository/docker/exadg/exadg/general). We will keep in mind the second variant described above https://github.com/exadg/exadg/pull/228#issuecomment-1326524155.

**Pull request closed without merging**
