### PR TITLE
use const as trailing keyword

### LINKED ISSUE #203: preCICE-based FSI code: follow coding convention "double const" (and similarily for all other types)
@DavidSCN: a follow up of #148

### PR DESCRIPTION
**Pull request by nfehn**
closes #203

### CODE REVIEW

**Comment by DavidSCN** [comment]
Thank you!

**Comment by nfehn** [comment]
@DavidSCN did you go through the changes? It would be good if someone else has briefly checked the changes before merging.

**Review by peterrum — APPROVED** [review]
A short question: have you done this manually or have used a script. In the latter case, it would be nice to make it part of the indentation check of CI.

**Comment by nfehn** [comment]
Unfortunately, only semi-manual. Run `contrib/utilities/search-and-replace-all` for all the data types that occur ;)

**Comment by nfehn** [comment]
If we collect all the data types that we know of in a file/vector, we could automatize this process and we would at least cover most of the cases automatically.

**Comment by nfehn** [comment]
For full automatization, we would need to detect data types automatically, which is not trivial since an empty character is not necessarily the end of the name `Type<int, bool>` for example. Also, how do we make sure that `double const value` is not changed to `double value const` by such a generic script?

**Pull request merged**
