### PR TITLE
Be explicit about unsteady problems

### PR DESCRIPTION
**Pull request by jh66637**
@nfehn 
Can you check if I forgot something?
Also I didn't find where the timestep is set -1, can you give me a hint?

### CODE REVIEW

**Comment by nfehn** [comment]
> Also I didn't find where the timestep is set -1, can you give me a hint?

Do you mean at the place where the function is called? I assume the parameter is justed not used in the `DriverSteadyProblem` classes when calling the postprocessor, see e.g. https://github.com/exadg/exadg/blob/b0f0d540fbdc8937fedaf9a5ed3d8930ffdc9464/include/exadg/convection_diffusion/time_integration/driver_steady_problems.cpp#L154, since the parameter `time_step_number` has a default argument. Or do I misunderstand something.

**Review by nfehn — APPROVED** [review]

**Comment by nfehn** [comment]
I think we can merge as soon as the code compiles without errors

**Comment by jh66637** [comment]
If you can confirm I didn't miss any place. I'm not confident here^^

**Comment by nfehn** [comment]
I think it looks good. We will go through it again anyway when adjusting the postprocessing modules according to `TimeControl`. Of course, it makes sense to test your new implementation for a single example with postprocessing (e.g. output or error computation).

**Comment by jh66637** [comment]
Is there a test or test case that covers an unsteady problem? If yes, which one, then I can test it

**Comment by nfehn** [comment]
The tests in ExaDG that you can run with ctest should include error calculations after a certain time interval, which would serve as a test here.

**Pull request merged**
