### PR TITLE
[WIP] Fix Compilation Errors

### PR DESCRIPTION
**Pull request by jh66637**
I think there are compilation errors related to explicitly using double and https://github.com/dealii/dealii/pull/14142

### CODE REVIEW

**Comment by nfehn** [comment]
hm, it is actually a design goal in ExaDG to keep  `Number` out of data structures such as `BoundaryDescriptor`. I am not sure if the changes here are the way how we should approach this.

**Comment by jh66637** [comment]
I am currently just checking where the error comes from. I am not intending to keep all the changes

**Comment by jh66637** [comment]
@nfehn The problem is, that deal checks internally for double vs float. So instantiating InterfaceCoupling<float> will fail. So you should not be allowed to call InterfaceCoupling and InterfaceCouplingData with Number==float in the first place if only doubles are supported inside.

**Comment by jh66637** [comment]
To be able to keep Number out, we need something like a copy of float data to double data. Or a major code refracturing. I might give it a try again towards the end of the week and create an Issue in the mean time.

**Pull request closed without merging**
